name: 🍎 macOS Builds
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
      lto:
        description: 'LTO mode. Options: "none", "thin", "full"'
        type: string
      repo:
        description: 'Repository to use for the build'
        type: string
      tag:
        description: 'tag to use for the build'
        type: string
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
      template_module_flags:
        description: 'Extra module flags for template build, e.g. module_webm_enabled=no'
        type: string

# Global Settings
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: ${{ inputs.base-branch }}
  SCONSFLAGS: verbose=yes warnings=extra werror=yes strict_checks=yes debug_symbols=no use_static_cpp=yes

jobs:
  build-macos:
    runs-on: macos-26
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            target: editor
            build-mono: false
            scons-mono-flags: ''

          - name: Template (target=template_release)
            target: template_release
            build-mono: false
            scons-mono-flags: ''
          
          - name: Template (target=template_debug)
            target: template_debug
            build-mono: false
            scons-mono-flags: ''

          - name: Editor Mono (target=editor)
            target: editor
            build-mono: true
            scons-mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_release)
            target: template_release
            build-mono: true
            scons-mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_debug)
            target: template_debug
            build-mono: true
            scons-mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Download pre-built ANGLE
        shell: sh
        id: angle-sdk
        run: |
          if python3 ./misc/scripts/install_angle.py; then
            echo "ANGLE_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::ANGLE SDK installation failed, building without ANGLE support."
            echo "ANGLE_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python3 ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: macos-${{ matrix.target }}-${{ matrix.scons-mono-flags }}-${{ inputs.lto }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Install Mono toolchain
        if: matrix.build-mono
        run: |
          brew list mono || brew install mono

      - name: Setup .NET SDK
        if: matrix.build-mono
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.100'

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Mono tools build (pre-glue)
        if: matrix.build-mono
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} arch=x86_64 ${{ inputs.lto }} ${{ inputs.module_flags }} module_mono_enabled=yes mono_glue=no angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: macos
          target: editor

      - name: Generate C# glue
        if: matrix.build-mono
        run: ./bin/godot.macos.editor.x86_64.mono --headless --generate-mono-glue ./modules/mono/glue

      - name: Compilation (x86_64 editor)
        if: matrix.target == 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} arch=x86_64 ${{ inputs.lto }} ${{ inputs.module_flags }} ${{ matrix.scons-mono-flags }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Compilation (arm64 editor)
        if: matrix.target == 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} arch=arm64 ${{ inputs.lto }} ${{ inputs.module_flags }} ${{ matrix.scons-mono-flags }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Compilation (x86_64 template)
        if: matrix.target != 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} arch=x86_64 ${{ inputs.lto }} ${{ inputs.template_module_flags }} ${{ matrix.scons-mono-flags }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Compilation (arm64 template)
        if: matrix.target != 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} arch=arm64 ${{ inputs.lto }} ${{ inputs.template_module_flags }} ${{ matrix.scons-mono-flags }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: macos
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: macos-${{ matrix.target }}-${{ matrix.scons-mono-flags }}-${{ inputs.lto }}
          purge-cache-script: misc/scripts/purge_cache.py
        continue-on-error: true

      - name: Build .NET solutions
        if: matrix.build-mono
        run: |
          dotnet --info
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos --werror

      - name: Prepare artifact
        run: |
          mono_suffix=""
          if [ "${{ matrix.build-mono }}" = 'true' ]; then
            mono_suffix=".mono"
          fi
          lipo -create ./bin/godot.macos.${{ matrix.target }}.x86_64${mono_suffix} ./bin/godot.macos.${{ matrix.target }}.arm64${mono_suffix} -output ./bin/godot.macos.${{ matrix.target }}${mono_suffix}.universal
          rm -rf ./bin/build_deps
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-${{ matrix.target }}${{ matrix.scons-mono-flags }}-${{ inputs.lto }}
          path: bin
