name: 🏁 Windows Builds
on:
  workflow_call:
    inputs:
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
      lto:
        description: 'LTO mode. Options: "none", "thin", "full"'
        type: string
      repo:
        description: 'Repository to use for the build'
        type: string
      tag:
        description: 'tag to use for the build'
        type: string
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
      template_module_flags:
        description: 'Extra module flags for template build, e.g. module_webm_enabled=no'
        type: string

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: ${{ inputs.base-branch }}
  SCONSFLAGS: verbose=yes warnings=extra strict_checks=yes debug_symbols=no ${{ inputs.module_flags }} use_static_cpp=yes
  SCONS_CACHE_MSVC_CONFIG: true
  PYTHONIOENCODING: utf8

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: windows-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor, arch=x86_64)
            target: editor
            scons-flags: arch=x86_64
            build-mono: false
            mono-flags: ''

          - name: Editor (target=editor, arch=arm64)
            target: editor
            scons-flags: arch=arm64
            build-mono: false
            mono-flags: ''

          - name: Template (target=template_release, arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64
            build-mono: false
            mono-flags: ''
          
          - name: Template (target=template_release, arch=x86)
            target: template_release
            scons-flags: arch=x86
            build-mono: false
            mono-flags: ''
          
          - name: Template (target=template_release, arch=arm64)
            target: template_release
            scons-flags: arch=arm64
            build-mono: false
            mono-flags: ''
          
          - name: Template (target=template_debug, arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64
            build-mono: false
            mono-flags: ''
          
          - name: Template (target=template_debug, arch=x86)
            target: template_debug
            scons-flags: arch=x86
            build-mono: false
            mono-flags: ''
          
          - name: Template (target=template_debug, arch=arm64)
            target: template_debug
            scons-flags: arch=arm64
            build-mono: false
            mono-flags: ''

          - name: Editor Mono (target=editor, arch=x86_64)
            target: editor
            scons-flags: arch=x86_64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_release, arch=x86_64)
            target: template_release
            scons-flags: arch=x86_64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_debug, arch=x86_64)
            target: template_debug
            scons-flags: arch=x86_64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Editor Mono (target=editor, arch=arm64)
            target: editor
            scons-flags: arch=arm64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_release, arch=arm64)
            target: template_release
            scons-flags: arch=arm64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

          - name: Template Mono (target=template_debug, arch=arm64)
            target: template_debug
            scons-flags: arch=arm64
            build-mono: true
            mono-flags: module_mono_enabled=yes mono_glue=yes mono_static=yes

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download Direct3D 12 SDK components
        shell: sh
        id: d3d12-sdk
        run: |
          if python ./misc/scripts/install_d3d12_sdk_windows.py; then
            echo "D3D12_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Windows: Direct3D 12 SDK installation failed, building without Direct3D 12 support."
            echo "D3D12_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi
        continue-on-error: true

      - name: Download pre-built ANGLE
        shell: sh
        id: angle-sdk
        run: |
          if python ./misc/scripts/install_angle.py; then
            echo "ANGLE_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::ANGLE SDK installation failed, building without ANGLE support."
            echo "ANGLE_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Download WinRT components
        shell: sh
        run: python ./misc/scripts/install_winrt.py
        continue-on-error: true

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

# Mono
      - name: Setup .NET SDK
        if: matrix.build-mono
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.100'

      - name: Mono tools build (pre-glue)
        if: matrix.build-mono
        uses: ./.github/actions/godot-build
        with:
          scons-flags: arch=x86_64 module_mono_enabled=yes mono_glue=no ${{ inputs.module_flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: windows
          target: editor

      - name: Generate C# glue
        if: matrix.build-mono
        run: |
          .\bin\godot.windows.editor.x86_64.mono.exe --headless --generate-mono-glue .\modules\mono\glue

# Compilation

      - name: Compilation (editor)
        if: matrix.target == 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ inputs.lto }} ${{ inputs.module_flags }} ${{ matrix.mono-flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: windows
          target: ${{ matrix.target }}

      - name: Compilation (template)
        if: matrix.target != 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.scons-flags }} ${{ inputs.lto }} ${{ inputs.template_module_flags }} ${{ matrix.mono-flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: windows
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
          purge-cache-script: misc/scripts/purge_cache.py
        continue-on-error: true

      - name: Build .NET solutions
        if: matrix.build-mono
        run: |
          dotnet --info
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=windows --werror

      - name: Prepare artifact
        run: |
          Remove-Item bin/build_deps -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-${{ matrix.target }}${{ matrix.mono-flags }}-${{ matrix.scons-flags }}-${{ inputs.lto }}
          path: bin
